project:
  type: website
  output-dir: docs

website:
  title: "Annette Loke"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
styles:
  - path: "styles.css"

format:
  html:
    theme: minty
    css: styles.css
    toc: true

content:
  - "Website_HTML_File.Rhtml"

editor: visual

