---
title: "<span style='font-family: Lemon Milk, sans-serif; color: #102828;'>Navigating the Singaporean Dream</span>"
format: html
---

```{=html}
<div class="left-align">
   <a href="https://github.com/annettel08/NM2207">Link to my NM2207 repository</a>
</div>
```

------------------------------------------------------------------------

## Exploring Rising Costs of Living, Income Disparities, and Educational Meritocracy

Talk of rising costs isn't just common in Singapore---it's nearly a national pastime, reflecting a universal concern of Singaporeans. Many lament that wages are not keeping up with the costs, adn this has incurred a lot of stress on many Singaporeans as a whole.

Yet, the impact of it is anything but uniform. It begs the question: In the face of an economic storm, are all Singaporeans sailing in the same boat, or are some navigating rougher waters with fewer resources?

Let's turn to the data to paint a clearer picture.

### Comparing CPI trends across income groups

Before I continue, i encourage you to play around witht eh visualisation below. To begin, choose a time period that you wish to view and which income groups you want to view and compare. Observe how the lines increase, and hover across the timeline to watch the numbers evolve. See firsthand the economic landscape that Singaporeans of different earnings have navigated over the years.

```{=html}
<iframe height="400" width="100%" frameborder="no" src="https://annettel08.shinyapps.io/CPI_trends/"> </iframe>
```
The Consumer Price Index (CPI) across 3 different income groups. The CPI is a critical measure that tracks the change in price of a common basket of goods and services over time, acting as a barometer for the cost of living. By comparing the CPI with income data, we can discern how various income groups are managing with the rising costs.

This chart brings about 2 big insights.

Firstly, notice how the once stark gap in CPI levels between the income groups has narrowed over time? This could suggest a leveling field, but the truth is more complex. For those who started off with less, this narrowing indicates not an easing of financial burdens, but a relative increase in the cost pressures they face. The expenses of the high income group have not lowered to meet the expenses of the low-income group, but rather, the low-income group's expenses have climbed so steeply that they now meet the expenses of the high-income group.

Secondly when we look at the line graphs as a whole, we notice that the CPI for the low-income group climbs at a pace that outstrips the rest. This is an important observation as it reflects the heightened challenges faced by lower-income earners, whose wages often struggle to keep pace with their daily expenses.

The combination of these observations show the increasing strain on those with the least financial flexibility, and partially answers our question: The tide of rising costs washes over all, but it's the low-income earners who are feeling the strongest pull against their efforts to stay afloat. However, why is it that they continue to face these struggles? What tools do they have to help them reach the level of the rest?

### Can I get rich by studying?

In Singapore, education has always been touted as a tool for meritocracy- in its ideal state, it is supposed to provide a level playing field, where hard work and talent lead to upward social mobility. Many youth are advised to focus on studies in their early years, to get a drgree or higher, and secure a better job. Yet, the persistent struggle of many, despite their educational achievements, raises questions about the efficacy of this tool in the meritocratic toolkit.

```{=html}
<iframe height="400" width="100%" frameborder="no" src="https://annettel08.shinyapps.io/prop_graduates/"> </iframe>
```
Consider this bar graph, which shows the proportion of youths enrolling in tertiary education institutions over the years. The bars rise incrementally, a testament to the fact that more young Singaporeans are hitting the books and earning their degrees. This upward trend should, in theory, correlate with an increased ability to navigate the economic waters with greater ease. However, this does not seem ot be the case- our rising Gini coefficient shows a widening gap in income disparity.

While the graph demonstrates a commendable increase in tertiary education enrollment, the waters of economic success remain choppy for many. The rising Gini coefficient---a measure of income inequality---tells a different tale. It signals that despite higher educational qualifications, the gap between the rich and the poor is not contracting, but rather, it's expanding.

This observation compels us to look beyond the graduation caps and gowns and to question the broader landscape. Why, if more youth are achieving higher levels of education, do we still see a struggle? It suggests that perhaps there are other, more formidable forces at play---social and economic factors that create undercurrents strong enough to keep certain segments of society from moving forward, despite their educational efforts.

Thus, the story that unfolds is not one-dimensional. It's a narrative that acknowledges the hard work of the youth, their dedication to education, and their commitment to bettering their futures. But it also recognizes that education, alone, is not a panacea. It is but one piece of a larger puzzle that must consider the complex interplay of social policies, economic structures, and the changing landscape of jobs and skills.

### Conclusion

In wrapping up this section, we find a key takeaway: The tide of rising costs washes over all, but it's the low-income earners who are feeling the strongest pull against their efforts to stay afloat. Education, long seen as a vessel for upward mobility, appears to be less capable of navigating them through these troubled waters than previously thought.

This data story isn't meant to be a tale of doom and gloom. Instead, it's a call to recognize the varied experiences of our fellow Singaporeans. It underscores the importance of policies and support tailored to those who are most vulnerable to the rising tides, ensuring that the journey towards financial stability is one that all can embark on, regardless of their starting point.
